### ISSUE TITLE
Enhancement proposal

### ISSUE THREAD

**Issue by Prometee** [coreshop/PayumStripeBundle#2]
Hi @ramundomario,

Would you be interested into having some abstract class or services into this https://github.com/FLUX-SE/PayumStripeBundle, to avoid copying all `*Provider` from the Sylius Plugin.
I think we can make something less painful for you and maybe more efficient if the core `*Provider` would be available into a root bundle (or into the root library).

What do you think about it ?

**Comment by ramundomario** [comment]
Hi @Prometee, first of all sorry for late reply (a litte bit busy...) and thanks a lot for your interest.

It would be nice to have some abstract class/services included in the Symfony bundle to be used in the [SylusBundle](https://github.com/FLUX-SE/SyliusPayumStripePlugin) and in this one.
Currently we are using the [Payum connector](https://github.com/FLUX-SE/PayumStripe) instead the [Symfony bundle](https://github.com/FLUX-SE/PayumStripeBundle) so we should switch, what do you think?

**Comment by Prometee** [comment]
@ramundomario I want to be able to make something working with any `Order` or `Payment` (ex: Payum payment, Sylius order, CoreShop order or any other models).

I hate `mixed` typing so I don't found a good and easy way of handling it yet...
If I get a clue I will come back to you 😉
