### ISSUE TITLE
Webhook not being used?

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/PayumStripeBundle#5]
The bundle does require a webhook key but it looks like it's never used. The FLUX-SE PayumStripe does define it here: https://github.com/FLUX-SE/PayumStripe/blob/6e8ad5b2415f01e8f7731daf593c0d27adc94244/docs/stripe-credentials.md#webhook-key
But the notify.php? url route is not included in this bundle as far as I can see.

Will payments be reported in coreshop without the webhook?

**Comment by ramundomario** [comment]
> The bundle does require a webhook key but it looks like it's never used. The FLUX-SE PayumStripe does define it here: https://github.com/FLUX-SE/PayumStripe/blob/6e8ad5b2415f01e8f7731daf593c0d27adc94244/docs/stripe-credentials.md#webhook-key
But the notify.php? url route is not included in this bundle as far as I can see.

Please see [Symfony bundle docs](https://github.com/FLUX-SE/PayumStripeBundle#webhook-key) regarding webhooks.
Be careful with the gateway in URL, with CoreShop, you have to use the identifier name you used to create the Payment Gateway in backend.

> Will payments be reported in coreshop without the webhook?

Payments will be reported even without webhook. It's just a double safety thing, from Stripe docs:

_The `checkout.session.completed` webhook is sent to your server before your customer is redirected. Your webhook acknowledgement (any `2xx` status code) triggers the customer’s redirect to the `success_url`. If Stripe doesn’t receive successful acknowledgement within 10 seconds of a successful payment, your customer is automatically redirected to the `success_url` page.
As the webhook must be acknowledged before redirecting the customer to the `success_url`​, you can be sure that the order was successful and can safely show a success message to your customer._

**Comment by Cruiser13** [comment]
Thank you for clarification @ramundomario !
