### ISSUE TITLE
[Stripe Checkout] Adjustments are ignored

### ISSUE THREAD

**Issue by Cruiser13** [coreshop/PayumStripeBundle#6]
Adjustments are ignored by the stripe payment bundle. If you do have a coreshop cart price rule, for example a coupon, which does reduce the price of the order, the subtotal value will be send to stripe instead of the total value.
This sample:
![adjustments](https://user-images.githubusercontent.com/2771909/119679867-ff93e900-be40-11eb-909c-8ff8eb19c8a4.png)

Will deduct 168 Euro (subtotal gross) of the credit card. Should be 151,2 Euro.

**Comment by ramundomario** [comment]
Thanks for reporting @Cruiser13.
I'm assuming you are using Stripe Checkout.
I did a bit of research and the only way apparently is to use [Stripe discount](https://stripe.com/docs/payments/checkout/discounts) as mentioned in this [discussion](https://stackoverflow.com/questions/67485220/how-to-add-a-negative-line-item-or-an-equivalent-of-a-discount-in-stripe-new-che) where a Stripe dev for this use case recommend using elements (Stripe JS).
It would have been much simpler if it were possible to include negative `line_item`, but unfortunately nope as mentioned also in stripe/stripe-node#906

**Comment by Cruiser13** [comment]
That's a pitty. Maybe we could solve it by sending on line item with the total as value instead of the single line items in this case?
So we'd end up with a position like "Shop cart" - 151,2 Euro as one line item?

**Comment by dpfaffenbauer** [comment]
Solution is to also take the OrderItem Adjustments into the line_item. CoreShop already breaks down the Cart Rules to the single items.

**Comment by ramundomario** [comment]
I tried as you advised with `$item->getTotal() - $item->getAdjustmentsTotal()` but `getAdjustmentsTotal()`, without args, returns `pimcoreAdjustmentTotalGross` which seems to be 0 with the cart price rules.
What do you advise? Thanks!

**Comment by dpfaffenbauer** [comment]
Sure. It's a bit more tricky than that. CoreShop saves the broken down cart rules as "neutral", so it doesn't affect the order-item-price. (Since we calculate the CartRules based on the cart, and not really on the items). 

You have to explicitly get all cart-rule adjustment in order to work. So something like `getAdjustments(AdjustmentInterface::CART_PRICE_RULE)` and then sum it up yourself per item.

**Comment by Cruiser13** [comment]
Thanks a lot @ramundomario !
