### ISSUE TITLE
Looking for documentation

### ISSUE THREAD

**Issue by valentin-** [coreshop/PayumStripeBundle#8]
Hi, is there any documentation how to setup the stripe payment provider?
I've tried different configs for the webhook secret and stripe config itself, but I can't get it working.

https://gitter.im/coreshop/CoreShop?at=61dc333e6d9ba23328b468b2

**Comment by ramundomario** [comment]
Hi @valentin-, please see #5 where i explained webhooks.
Note: on the Gitter channel you mentioned CoreShop 3. 
At the moment this bundle has not been tested and is not usable with CoreShop 3 as indicated in [composer.json](https://github.com/coreshop/PayumStripeBundle/blob/b728b2204470820ae3741c6304d8b30cfd9cacc3/composer.json#L24).
